//! PostgreSQL implementations of the auth session transaction traits.
//!
//! This module contains the concrete database logic for creating, pinging, and deleting
//! auth sessions in a PostgreSQL database. Each function is annotated with the
//! [`#[db_transaction]`](crate::db_transaction) attribute macro, which implements the
//! corresponding trait (defined in [`tx_definitions`](super::tx_definitions)) on
//! [`AuthPostGresDescriptor<T>`](crate::dal::connections::AuthPostGresDescriptor).
//!
//! # How it works
//!
//! The `#[db_transaction(AuthPostGresDescriptor, TraitName)]` macro expands each function
//! into an `impl<T: YieldPostGresPool> TraitName for AuthPostGresDescriptor<T>` block.
//! Inside the function body, `T::yield_pool()` provides a reference to the connection pool
//! (`&'static Pool<Postgres>`), which is used to execute queries.
//!
//! # Schema
//!
//! All queries target the `saps` schema. The table and supporting `ping` function can be
//! created by calling [`AuthSession::generate_migration_sql()`](super::model::AuthSession::generate_migration_sql).
//!
//! # Generic `U: UserRole`
//!
//! The `role` column is stored as `VARCHAR`. When inserting, the role is converted
//! to a string via `ToString`. When reading, the raw string is parsed back into `U` via
//! `TryFrom<String>` (both provided by the [`UserRole`] trait).
//! This means any role enum generated by [`construct_checks!`](crate::construct_checks) works
//! out of the box.
//!
//! # Example
//!
//! ```ignore
//! use saps::dal::connections::{AuthPostGresDescriptor, LivePostGresPool};
//! use saps::auth::dal::tx_definitions::{CreateAuthSession, PingAuthSession, DeleteAuthSession};
//! use saps::auth::dal::model::AuthSession;
//!
//! // Create a new session
//! let session = AuthSession::new(MyRole::Admin);
//! let created = AuthPostGresDescriptor::<LivePostGresPool>::create_auth_session(session).await?;
//!
//! // Ping the session (extends last_interacted, returns None if expired)
//! let active = AuthPostGresDescriptor::<LivePostGresPool>::ping_auth_session::<MyRole>(30, created.id).await?;
//!
//! // Delete the session
//! let deleted = AuthPostGresDescriptor::<LivePostGresPool>::delete_auth_session(created.id).await?;
//! ```

use super::{
    model::AuthSession,
    tx_definitions::{
        CompareAndSwapAuthSessionMeta, CreateAuthSession, DeleteAuthSession,
        DeleteAuthSessionMetaKey, DeleteAuthSessionsByMetaKey, DeleteAuthSessionsByMetaKeyPair,
        GetAllAuthSessions, GetAuthSession,
        GetAuthSessionByMetaKey, GetAuthSessionByMetaKeyStrict, GetAuthSessionStrict,
        GetAuthSessionsByMetaKey, GetAuthSessionsByMetaKeyPair, PingAuthSession,
        UpdateAuthSessionMeta, UpsertAuthSessionMetaKey,
        UpsertAuthSessionsMetaKeyByMeta,
    },
};
use crate::{
    auth::token::checks::UserRole, dal::connections::AuthPostGresDescriptor, db_transaction,
};
use serde_json::Value;

/// Inserts a new auth session into `saps.auth_sessions`.
///
/// The caller constructs an [`AuthSession`] (typically via [`AuthSession::new`]) and this
/// function persists it to the database. The `role` is stored as a lowercase string
/// via `ToString`. The full row is returned from the `RETURNING` clause and parsed back
/// into an `AuthSession<U>`.
///
/// # Errors
///
/// Returns `sqlx::Error` if:
/// - The insert fails (e.g. constraint violation)
/// - The returned `role` string cannot be parsed back into `U`
#[db_transaction(AuthPostGresDescriptor, CreateAuthSession)]
async fn create_auth_session<U: UserRole>(session: AuthSession<U>) -> AuthSession<U> {
    let pool = T::yield_pool();
    let row = sqlx::query(
        r#"
        INSERT INTO saps.auth_sessions (id, old_id, role, date_created, last_interacted, time_minted, meta)
        VALUES ($1, $1, $2, $3, $4, $3, $5)
        RETURNING id, role, date_created, last_interacted, meta
        "#,
    )
    .bind(session.id)
    .bind(session.role.to_string())
    .bind(session.date_created)
    .bind(session.last_interacted)
    .bind(session.meta)
    .fetch_one(pool)
    .await?;
    AuthSession::from_row(&row).map_err(|e| sqlx::Error::Protocol(e.message))
}

/// Pings an existing auth session by calling the `saps.ping` PostgreSQL function.
///
/// The `saps.ping(p_minutes, p_session_id)` function performs the following atomically:
/// 1. If the session's `last_interacted` is older than `p_minutes` ago, it **deletes**
///    the expired session and returns `NULL`.
/// 2. If the session is still valid, it **updates** `last_interacted` to `NOW()` and
///    returns the updated row.
/// 3. If no session exists for the given id, it returns `NULL`.
///
/// This function maps `NULL` to `None` and a valid row to `Some(AuthSession<U>)`.
///
/// # Arguments
///
/// * `minutes` - The session timeout in minutes. Sessions older than this are expired.
/// * `session_id` - The UUID of the session to ping.
///
/// # Errors
///
/// Returns `sqlx::Error` if:
/// - The query fails
/// - The returned `role` string cannot be parsed back into `U`
#[db_transaction(AuthPostGresDescriptor, PingAuthSession)]
async fn ping_auth_session<U: UserRole>(minutes: i32, session_id: &str) -> Option<AuthSession<U>> {
    let pool = T::yield_pool();
    let parsed_id: uuid::Uuid = session_id
        .parse()
        .map_err(|e| sqlx::Error::Protocol(format!("invalid session_id UUID: {}", e)))?;
    let row = sqlx::query("SELECT * FROM saps.ping($1, $2)")
        .bind(minutes)
        .bind(parsed_id)
        .fetch_optional(pool)
        .await?;
    match row {
        Some(r) => {
            // The ping function returns NULL as a composite row when the session is
            // expired or missing. Postgres still delivers a row with all-null columns,
            // so we check the id column before attempting to parse.
            let id: Option<uuid::Uuid> = sqlx::Row::try_get(&r, "id")
                .map_err(|e: sqlx::Error| sqlx::Error::Protocol(e.to_string()))?;
            if id.is_none() {
                return Ok(None);
            }
            let session =
                AuthSession::from_row(&r).map_err(|e| sqlx::Error::Protocol(e.message))?;
            Ok(Some(session))
        }
        None => Ok(None),
    }
}

/// Returns all auth sessions from `saps.auth_sessions`.
///
/// Each row's `role` VARCHAR is parsed back into `U` via `TryFrom<String>`.
///
/// # Errors
///
/// Returns `sqlx::Error` if:
/// - The query fails
/// - Any row's `role` string cannot be parsed into `U`
#[db_transaction(AuthPostGresDescriptor, GetAllAuthSessions)]
async fn get_all_auth_sessions<U: UserRole>() -> Vec<AuthSession<U>> {
    let pool = T::yield_pool();
    let rows =
        sqlx::query("SELECT id, role, date_created, last_interacted, meta FROM saps.auth_sessions")
            .fetch_all(pool)
            .await?;
    let mut sessions = Vec::with_capacity(rows.len());
    for row in &rows {
        sessions.push(AuthSession::from_row(row).map_err(|e| sqlx::Error::Protocol(e.message))?);
    }
    Ok(sessions)
}

/// Fetches a single auth session by its id.
///
/// Returns `Some(AuthSession<U>)` if a row exists with the given id, or `None`
/// if no session is found. The `role` VARCHAR is parsed back into `U` via
/// `TryFrom<String>`.
///
/// # Arguments
///
/// * `session_id` - The UUID of the session to fetch, as a string.
///
/// # Errors
///
/// Returns `sqlx::Error` if:
/// - The `session_id` is not a valid UUID
/// - The query fails
/// - The returned `role` string cannot be parsed back into `U`
#[db_transaction(AuthPostGresDescriptor, GetAuthSession)]
async fn get_auth_session<U: UserRole>(session_id: &str) -> Option<AuthSession<U>> {
    let pool = T::yield_pool();
    let parsed_id: uuid::Uuid = session_id
        .parse()
        .map_err(|e| sqlx::Error::Protocol(format!("invalid session_id UUID: {}", e)))?;
    let row = sqlx::query(
        "SELECT id, role, date_created, last_interacted, meta FROM saps.auth_sessions WHERE id = $1"
    )
        .bind(parsed_id)
        .fetch_optional(pool)
        .await?;
    match row {
        Some(r) => {
            let session =
                AuthSession::from_row(&r).map_err(|e| sqlx::Error::Protocol(e.message))?;
            Ok(Some(session))
        }
        None => Ok(None),
    }
}

/// Strict variant of [`get_auth_session`] that returns
/// `sqlx::Error::RowNotFound` instead of `Ok(None)` when no session matches.
///
/// Useful when the caller has already established that the session must
/// exist (e.g. its id came from a token that was just validated) and wants
/// the missing-row case to surface as an error rather than as
/// `Option::None`.
///
/// # Errors
///
/// Returns `sqlx::Error` if:
/// - The `session_id` is not a valid UUID
/// - No session exists with that id (`sqlx::Error::RowNotFound`)
/// - The query fails
/// - The returned `role` string cannot be parsed back into `U`
#[db_transaction(AuthPostGresDescriptor, GetAuthSessionStrict)]
async fn get_auth_session_strict<U: UserRole>(session_id: &str) -> AuthSession<U> {
    let pool = T::yield_pool();
    let parsed_id: uuid::Uuid = session_id
        .parse()
        .map_err(|e| sqlx::Error::Protocol(format!("invalid session_id UUID: {}", e)))?;
    let row = sqlx::query(
        "SELECT id, role, date_created, last_interacted, meta FROM saps.auth_sessions WHERE id = $1"
    )
        .bind(parsed_id)
        .fetch_one(pool)
        .await?;
    AuthSession::from_row(&row).map_err(|e| sqlx::Error::Protocol(e.message))
}

/// Replaces the `meta` JSON for an existing auth session.
///
/// Updates the `meta` column of the row matching `session_id` with the supplied
/// JSON value. No error is returned if the session does not exist; the update
/// simply affects zero rows.
///
/// # Arguments
///
/// * `session_id` - The UUID of the session to update, as a string.
/// * `meta` - The JSON value to store in the `meta` column.
///
/// # Errors
///
/// Returns `sqlx::Error` if:
/// - The `session_id` is not a valid UUID
/// - The query fails
#[db_transaction(AuthPostGresDescriptor, UpdateAuthSessionMeta)]
async fn update_auth_session_meta(session_id: &str, meta: Value) -> () {
    let pool = T::yield_pool();
    let parsed_id: uuid::Uuid = session_id
        .parse()
        .map_err(|e| sqlx::Error::Protocol(format!("invalid session_id UUID: {}", e)))?;
    sqlx::query("UPDATE saps.auth_sessions SET meta = $1 WHERE id = $2")
        .bind(meta)
        .bind(parsed_id)
        .execute(pool)
        .await?;
    Ok(())
}

/// Sets a single key in the `meta` JSON of an existing auth session, leaving
/// all other keys intact, and returns the updated session.
///
/// If `meta` is `NULL`, it is treated as an empty object before the key is
/// inserted. If the key already exists, its value is overwritten; all other
/// keys are preserved. The merge happens server-side via `jsonb_set` so the
/// update is atomic with respect to concurrent writers. Returns
/// `Some(AuthSession<U>)` with the post-update row, or `None` if no session
/// exists for `session_id`.
///
/// # Arguments
///
/// * `session_id` - The UUID of the session to update, as a string.
/// * `key` - The top-level key to insert or overwrite in the `meta` object.
/// * `value` - The JSON value to associate with `key`.
///
/// # Errors
///
/// Returns `sqlx::Error` if:
/// - The `session_id` is not a valid UUID
/// - The query fails
/// - The returned `role` string cannot be parsed back into `U`
#[db_transaction(AuthPostGresDescriptor, UpsertAuthSessionMetaKey)]
async fn upsert_auth_session_meta_key<U: UserRole>(
    session_id: &str,
    key: &str,
    value: Value,
) -> Option<AuthSession<U>> {
    let pool = T::yield_pool();
    let parsed_id: uuid::Uuid = session_id
        .parse()
        .map_err(|e| sqlx::Error::Protocol(format!("invalid session_id UUID: {}", e)))?;
    let row = sqlx::query(
        "UPDATE saps.auth_sessions \
         SET meta = jsonb_set(COALESCE(meta, '{}'::jsonb), ARRAY[$1], $2, true) \
         WHERE id = $3 \
         RETURNING id, role, date_created, last_interacted, meta",
    )
        .bind(key)
        .bind(value)
        .bind(parsed_id)
        .fetch_optional(pool)
        .await?;
    match row {
        Some(r) => {
            let session =
                AuthSession::from_row(&r).map_err(|e| sqlx::Error::Protocol(e.message))?;
            Ok(Some(session))
        }
        None => Ok(None),
    }
}

/// Atomic compare-and-swap on a single top-level key in `meta`.
///
/// Updates `meta[key]` to `new_value` only if the current value at `key`
/// equals `expected`. The check and the write happen in a single
/// `UPDATE ... WHERE` so concurrent writers can't slip in between the read
/// and the write.
///
/// Returns `Some(AuthSession<U>)` with the post-update row when the swap
/// succeeded, or `None` when:
/// - The session does not exist,
/// - The key is absent from `meta` (or `meta` is `NULL`),
/// - The current value at `key` does not equal `expected`.
///
/// JSONB equality semantics apply: an explicit JSON `null` at `key` matches
/// an `expected` of `Value::Null`, but a missing key never matches anything
/// (because `meta -> 'missing'` is SQL `NULL` and `NULL = anything` is
/// unknown, so the row is filtered out).
///
/// # Arguments
///
/// * `session_id` - The UUID of the session to update, as a string.
/// * `key` - The top-level key in `meta` to compare and swap.
/// * `expected` - The JSON value that `meta[key]` must currently equal.
/// * `new_value` - The JSON value to write if the comparison matches.
///
/// # Errors
///
/// Returns `sqlx::Error` if:
/// - The `session_id` is not a valid UUID
/// - The query fails
/// - The returned `role` string cannot be parsed back into `U`
#[db_transaction(AuthPostGresDescriptor, CompareAndSwapAuthSessionMeta)]
async fn compare_and_swap_auth_session_meta<U: UserRole>(
    session_id: &str,
    key: &str,
    expected: Value,
    new_value: Value,
) -> Option<AuthSession<U>> {
    let pool = T::yield_pool();
    let parsed_id: uuid::Uuid = session_id
        .parse()
        .map_err(|e| sqlx::Error::Protocol(format!("invalid session_id UUID: {}", e)))?;
    let row = sqlx::query(
        "UPDATE saps.auth_sessions \
         SET meta = jsonb_set(meta, ARRAY[$2], $4, true) \
         WHERE id = $1 AND meta -> $2 = $3 \
         RETURNING id, role, date_created, last_interacted, meta",
    )
        .bind(parsed_id)
        .bind(key)
        .bind(expected)
        .bind(new_value)
        .fetch_optional(pool)
        .await?;
    match row {
        Some(r) => {
            let session =
                AuthSession::from_row(&r).map_err(|e| sqlx::Error::Protocol(e.message))?;
            Ok(Some(session))
        }
        None => Ok(None),
    }
}

/// Removes a single top-level key from the `meta` JSON of an existing auth
/// session, leaving all other keys intact, and returns the updated session.
///
/// Uses the PostgreSQL `jsonb - text` operator, which strips the named key
/// from a JSONB object. If `meta` is `NULL` the column stays `NULL`. If the
/// key is absent the row is rewritten unchanged. Other keys are preserved.
/// Returns `Some(AuthSession<U>)` with the post-update row, or `None` if no
/// session exists for `session_id`.
///
/// # Arguments
///
/// * `session_id` - The UUID of the session to update, as a string.
/// * `key` - The top-level key to remove from the `meta` object.
///
/// # Errors
///
/// Returns `sqlx::Error` if:
/// - The `session_id` is not a valid UUID
/// - The query fails
/// - The returned `role` string cannot be parsed back into `U`
#[db_transaction(AuthPostGresDescriptor, DeleteAuthSessionMetaKey)]
async fn delete_auth_session_meta_key<U: UserRole>(
    session_id: &str,
    key: &str,
) -> Option<AuthSession<U>> {
    let pool = T::yield_pool();
    let parsed_id: uuid::Uuid = session_id
        .parse()
        .map_err(|e| sqlx::Error::Protocol(format!("invalid session_id UUID: {}", e)))?;
    let row = sqlx::query(
        "UPDATE saps.auth_sessions SET meta = meta - $1 WHERE id = $2 \
         RETURNING id, role, date_created, last_interacted, meta",
    )
        .bind(key)
        .bind(parsed_id)
        .fetch_optional(pool)
        .await?;
    match row {
        Some(r) => {
            let session =
                AuthSession::from_row(&r).map_err(|e| sqlx::Error::Protocol(e.message))?;
            Ok(Some(session))
        }
        None => Ok(None),
    }
}

/// Returns every auth session whose `meta` contains the given key/value pair.
///
/// Uses the JSONB containment operator `@>`, so `meta` must include the named
/// key with a value equal to `value` (other keys are ignored). Sessions whose
/// `meta` is `NULL` never match. The query is index-friendly with a GIN index
/// on `meta`.
///
/// # Arguments
///
/// * `key` - The top-level key to look for in `meta`.
/// * `value` - The JSON value the key must equal.
///
/// # Errors
///
/// Returns `sqlx::Error` if:
/// - The query fails
/// - Any row's `role` string cannot be parsed back into `U`
#[db_transaction(AuthPostGresDescriptor, GetAuthSessionsByMetaKey)]
async fn get_auth_sessions_by_meta_key<U: UserRole>(
    key: &str,
    value: Value,
) -> Vec<AuthSession<U>> {
    let pool = T::yield_pool();
    let rows = sqlx::query(
        "SELECT id, role, date_created, last_interacted, meta \
         FROM saps.auth_sessions \
         WHERE meta @> jsonb_build_object($1::text, $2::jsonb)",
    )
        .bind(key)
        .bind(value)
        .fetch_all(pool)
        .await?;
    let mut sessions = Vec::with_capacity(rows.len());
    for row in &rows {
        sessions.push(AuthSession::from_row(row).map_err(|e| sqlx::Error::Protocol(e.message))?);
    }
    Ok(sessions)
}

/// Returns at most one auth session whose `meta` contains the given key/value
/// pair.
///
/// Designed to be paired with a partial unique index on `meta->>key` (see
/// [`AuthSession::generate_unique_meta_key_sql`](super::model::AuthSession::generate_unique_meta_key_sql)),
/// where the index guarantees that at most one row can match. The query
/// itself uses `LIMIT 1` so it stays correct even if the unique index is
/// missing — it just becomes "any one matching row" in that case.
///
/// # Arguments
///
/// * `key` - The top-level key to look for in `meta`.
/// * `value` - The JSON value the key must equal.
///
/// # Errors
///
/// Returns `sqlx::Error` if:
/// - The query fails
/// - The returned `role` string cannot be parsed back into `U`
#[db_transaction(AuthPostGresDescriptor, GetAuthSessionByMetaKey)]
async fn get_auth_session_by_meta_key<U: UserRole>(
    key: &str,
    value: Value,
) -> Option<AuthSession<U>> {
    let pool = T::yield_pool();
    let row = sqlx::query(
        "SELECT id, role, date_created, last_interacted, meta \
         FROM saps.auth_sessions \
         WHERE meta @> jsonb_build_object($1::text, $2::jsonb) \
         LIMIT 1",
    )
        .bind(key)
        .bind(value)
        .fetch_optional(pool)
        .await?;
    match row {
        Some(r) => {
            let session =
                AuthSession::from_row(&r).map_err(|e| sqlx::Error::Protocol(e.message))?;
            Ok(Some(session))
        }
        None => Ok(None),
    }
}

/// Strict variant of [`get_auth_session_by_meta_key`] that returns
/// `sqlx::Error::RowNotFound` instead of `Ok(None)` when no session contains
/// the given key/value pair.
///
/// Same containment lookup with `LIMIT 1` semantics — pair with the partial
/// unique index from
/// [`AuthSession::generate_unique_meta_key_sql`](super::model::AuthSession::generate_unique_meta_key_sql)
/// to guarantee the result is the unique match. Useful when the caller is
/// certain the session exists and wants the missing-row case to error
/// rather than return `None`.
///
/// # Errors
///
/// Returns `sqlx::Error` if:
/// - No session matches the key/value pair (`sqlx::Error::RowNotFound`)
/// - The query fails
/// - The returned `role` string cannot be parsed back into `U`
#[db_transaction(AuthPostGresDescriptor, GetAuthSessionByMetaKeyStrict)]
async fn get_auth_session_by_meta_key_strict<U: UserRole>(
    key: &str,
    value: Value,
) -> AuthSession<U> {
    let pool = T::yield_pool();
    let row = sqlx::query(
        "SELECT id, role, date_created, last_interacted, meta \
         FROM saps.auth_sessions \
         WHERE meta @> jsonb_build_object($1::text, $2::jsonb) \
         LIMIT 1",
    )
        .bind(key)
        .bind(value)
        .fetch_one(pool)
        .await?;
    AuthSession::from_row(&row).map_err(|e| sqlx::Error::Protocol(e.message))
}

/// Returns every auth session whose `meta` contains both `(key1, value1)` and
/// `(key2, value2)`.
///
/// Designed to be paired with the composite partial unique index from
/// [`AuthSession::generate_unique_meta_key_pair_sql`](super::model::AuthSession::generate_unique_meta_key_pair_sql),
/// where the index guarantees the result is at most one row — e.g. looking up
/// a session by `("user_id", N, "server_tag", "app")`. The query stays correct
/// without the index; it just degenerates to "all matching rows" in that case,
/// which is why the return type is `Vec<AuthSession<U>>` rather than `Option`.
///
/// Uses the JSONB containment operator `@>` so the same GIN index that
/// accelerates [`get_auth_sessions_by_meta_key`] also accelerates this query
/// if one is installed.
///
/// # Arguments
///
/// * `key1` - The first top-level key to look for in `meta`.
/// * `value1` - The JSON value the first key must equal.
/// * `key2` - The second top-level key to look for in `meta`.
/// * `value2` - The JSON value the second key must equal.
///
/// # Errors
///
/// Returns `sqlx::Error` if:
/// - The query fails
/// - Any row's `role` string cannot be parsed back into `U`
#[db_transaction(AuthPostGresDescriptor, GetAuthSessionsByMetaKeyPair)]
async fn get_auth_sessions_by_meta_key_pair<U: UserRole>(
    key1: &str,
    value1: Value,
    key2: &str,
    value2: Value,
) -> Vec<AuthSession<U>> {
    let pool = T::yield_pool();
    let rows = sqlx::query(
        "SELECT id, role, date_created, last_interacted, meta \
         FROM saps.auth_sessions \
         WHERE meta @> jsonb_build_object($1::text, $2::jsonb, $3::text, $4::jsonb)",
    )
        .bind(key1)
        .bind(value1)
        .bind(key2)
        .bind(value2)
        .fetch_all(pool)
        .await?;
    let mut sessions = Vec::with_capacity(rows.len());
    for row in &rows {
        sessions.push(AuthSession::from_row(row).map_err(|e| sqlx::Error::Protocol(e.message))?);
    }
    Ok(sessions)
}

/// Sets `upsert_key`/`upsert_value` on every session whose `meta` matches
/// `match_key`/`match_value`, returning the number of rows that were updated.
///
/// Combines [`get_auth_sessions_by_meta_key`] (containment lookup) and
/// [`upsert_auth_session_meta_key`] (jsonb_set with `create_missing`) into a
/// single statement so the lookup and the write happen atomically. `meta` is
/// coalesced from `NULL` to `'{}'::jsonb` before the upsert, so a row that
/// only carries the match key (and has no other meta) still gets the new
/// key inserted.
///
/// Pair this with a partial unique index on `match_key` (see
/// [`AuthSession::generate_unique_meta_key_sql`](super::model::AuthSession::generate_unique_meta_key_sql))
/// to guarantee the return value is `0` or `1`. Without the index, every
/// session whose `meta` contains the matching pair is updated.
///
/// # Arguments
///
/// * `match_key` - Top-level key used to find the target session(s).
/// * `match_value` - JSON value the match key must equal.
/// * `upsert_key` - Top-level key to insert or overwrite in `meta`.
/// * `upsert_value` - JSON value to associate with `upsert_key`.
///
/// # Errors
///
/// Returns `sqlx::Error` if the query fails.
#[db_transaction(AuthPostGresDescriptor, UpsertAuthSessionsMetaKeyByMeta)]
async fn upsert_auth_sessions_meta_key_by_meta(
    match_key: &str,
    match_value: Value,
    upsert_key: &str,
    upsert_value: Value,
) -> u64 {
    let pool = T::yield_pool();
    let result = sqlx::query(
        "UPDATE saps.auth_sessions \
         SET meta = jsonb_set(COALESCE(meta, '{}'::jsonb), ARRAY[$3], $4, true) \
         WHERE meta @> jsonb_build_object($1::text, $2::jsonb)",
    )
        .bind(match_key)
        .bind(match_value)
        .bind(upsert_key)
        .bind(upsert_value)
        .execute(pool)
        .await?;
    Ok(result.rows_affected())
}

/// Deletes every auth session whose `meta` contains the given key/value pair.
///
/// Uses the JSONB containment operator `@>` to match rows where `meta`
/// includes `key` with a value equal to `value`. Returns the number of rows
/// removed.
///
/// # Arguments
///
/// * `key` - The top-level key to look for in `meta`.
/// * `value` - The JSON value the key must equal.
///
/// # Errors
///
/// Returns `sqlx::Error` if the query fails.
#[db_transaction(AuthPostGresDescriptor, DeleteAuthSessionsByMetaKey)]
async fn delete_auth_sessions_by_meta_key(key: &str, value: Value) -> u64 {
    let pool = T::yield_pool();
    let result = sqlx::query(
        "DELETE FROM saps.auth_sessions \
         WHERE meta @> jsonb_build_object($1::text, $2::jsonb)",
    )
        .bind(key)
        .bind(value)
        .execute(pool)
        .await?;
    Ok(result.rows_affected())
}

/// Deletes every auth session whose `meta` contains both `(key1, value1)` and
/// `(key2, value2)`.
///
/// Pair-scoped counterpart of [`delete_auth_sessions_by_meta_key`] — uses the
/// JSONB containment operator `@>` to match rows whose `meta` includes both
/// key/value pairs, leaving rows that match only one (or neither) untouched.
/// Designed to target the same sessions that
/// [`get_auth_sessions_by_meta_key_pair`] returns, i.e. one specific
/// `(user_id, server_tag)` row when the composite unique index from
/// [`AuthSession::generate_unique_meta_key_pair_sql`](super::model::AuthSession::generate_unique_meta_key_pair_sql)
/// is installed.
///
/// Returns the number of rows removed.
///
/// # Arguments
///
/// * `key1` - The first top-level key to look for in `meta`.
/// * `value1` - The JSON value the first key must equal.
/// * `key2` - The second top-level key to look for in `meta`.
/// * `value2` - The JSON value the second key must equal.
///
/// # Errors
///
/// Returns `sqlx::Error` if the query fails.
#[db_transaction(AuthPostGresDescriptor, DeleteAuthSessionsByMetaKeyPair)]
async fn delete_auth_sessions_by_meta_key_pair(
    key1: &str,
    value1: Value,
    key2: &str,
    value2: Value,
) -> u64 {
    let pool = T::yield_pool();
    let result = sqlx::query(
        "DELETE FROM saps.auth_sessions \
         WHERE meta @> jsonb_build_object($1::text, $2::jsonb, $3::text, $4::jsonb)",
    )
        .bind(key1)
        .bind(value1)
        .bind(key2)
        .bind(value2)
        .execute(pool)
        .await?;
    Ok(result.rows_affected())
}

/// Deletes an auth session by its UUID.
///
/// Removes the row from `saps.auth_sessions` where `id` matches. Returns `true`
/// if a row was deleted, `false` if no session existed with that id.
///
/// # Arguments
///
/// * `session_id` - The UUID of the session to delete.
///
/// # Errors
///
/// Returns `sqlx::Error` if the query fails.
#[db_transaction(AuthPostGresDescriptor, DeleteAuthSession)]
async fn delete_auth_session(session_id: uuid::Uuid) -> bool {
    let pool = T::yield_pool();
    let result = sqlx::query("DELETE FROM saps.auth_sessions WHERE id = $1")
        .bind(session_id)
        .execute(pool)
        .await?;
    Ok(result.rows_affected() > 0)
}

// MARK: - Tests

#[cfg(test)]
mod tests {
    use super::*;
    use crate::auth::dal::tx_definitions::{CreateAuthSession, PingAuthSession};
    use crate::errors::saps::SapsError;
    use serde::{Deserialize, Serialize};

    #[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
    enum TestRole {
        Admin,
        Customer,
    }

    impl std::fmt::Display for TestRole {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            match self {
                TestRole::Admin => write!(f, "admin"),
                TestRole::Customer => write!(f, "customer"),
            }
        }
    }

    impl TryFrom<String> for TestRole {
        type Error = SapsError;
        fn try_from(value: String) -> Result<Self, Self::Error> {
            match value.to_lowercase().as_str() {
                "admin" => Ok(TestRole::Admin),
                "customer" => Ok(TestRole::Customer),
                _ => Err(SapsError::bad_request(format!("Unknown role: {}", value))),
            }
        }
    }

    impl crate::auth::token::checks::UserRole for TestRole {}

    /// Fetches the raw `id`, `old_id`, and `time_minted` for a session via
    /// `last_interacted` lookup. The id may have rotated, so we look up the
    /// single row that exists.
    async fn fetch_row_state(
        pool: &saps::sqlx::Pool<saps::sqlx::Postgres>,
    ) -> (uuid::Uuid, uuid::Uuid, chrono::NaiveDateTime) {
        let row = saps::sqlx::query(
            "SELECT id, old_id, time_minted FROM saps.auth_sessions LIMIT 1",
        )
        .fetch_one(pool)
        .await
        .expect("fetch row state");
        let id: uuid::Uuid = saps::sqlx::Row::try_get(&row, "id").expect("id");
        let old_id: uuid::Uuid = saps::sqlx::Row::try_get(&row, "old_id").expect("old_id");
        let time_minted: chrono::NaiveDateTime =
            saps::sqlx::Row::try_get(&row, "time_minted").expect("time_minted");
        (id, old_id, time_minted)
    }

    #[saps::db_test]
    async fn test_create_initialises_old_id_to_id() {
        let session = AuthSession::new(TestRole::Admin);
        let created = AuthPostGresDescriptor::<TestDbHandle>::create_auth_session(session)
            .await
            .expect("create session");

        let (id, old_id, _time_minted) = fetch_row_state(pool).await;
        assert_eq!(id, created.id);
        assert_eq!(old_id, created.id);
    }

    #[saps::db_test]
    async fn test_rotation_sets_old_id_and_resets_time_minted() {
        let session = AuthSession::new(TestRole::Admin);
        let created = AuthPostGresDescriptor::<TestDbHandle>::create_auth_session(session)
            .await
            .expect("create session");

        // Backdate so the next ping triggers rotation (date_created > 5 mins).
        // time_minted is also backdated so we can confirm rotation refreshes it.
        saps::sqlx::query(
            "UPDATE saps.auth_sessions \
             SET date_created = NOW() - INTERVAL '10 minutes', \
                 time_minted = NOW() - INTERVAL '10 minutes' \
             WHERE id = $1",
        )
        .bind(created.id)
        .execute(pool)
        .await
        .expect("backdate session");

        let pinged = AuthPostGresDescriptor::<TestDbHandle>::ping_auth_session::<TestRole>(
            30,
            &created.id.to_string(),
        )
        .await
        .expect("ping session")
        .expect("session should exist");

        assert_ne!(pinged.id, created.id, "id should have rotated");

        let (db_id, db_old_id, db_time_minted) = fetch_row_state(pool).await;
        assert_eq!(db_id, pinged.id);
        assert_eq!(db_old_id, created.id, "old_id should be the pre-rotation id");
        assert!(
            db_time_minted > chrono::Utc::now().naive_utc() - chrono::Duration::seconds(5),
            "time_minted should have been refreshed on rotation"
        );
    }

    #[saps::db_test]
    async fn test_ping_with_old_id_within_grace_period_succeeds_without_rotating() {
        let session = AuthSession::new(TestRole::Admin);
        let created = AuthPostGresDescriptor::<TestDbHandle>::create_auth_session(session)
            .await
            .expect("create session");

        // Force the first ping to rotate.
        saps::sqlx::query(
            "UPDATE saps.auth_sessions \
             SET date_created = NOW() - INTERVAL '10 minutes' \
             WHERE id = $1",
        )
        .bind(created.id)
        .execute(pool)
        .await
        .expect("backdate session");

        let after_rotation =
            AuthPostGresDescriptor::<TestDbHandle>::ping_auth_session::<TestRole>(
                30,
                &created.id.to_string(),
            )
            .await
            .expect("ping rotates")
            .expect("session should exist");
        assert_ne!(after_rotation.id, created.id);

        // An inflight request still using the original id arrives during the
        // grace window — should succeed and return the current (rotated) row
        // without rotating again.
        let inflight =
            AuthPostGresDescriptor::<TestDbHandle>::ping_auth_session::<TestRole>(
                30,
                &created.id.to_string(),
            )
            .await
            .expect("inflight ping")
            .expect("session should still be reachable via old_id");

        assert_eq!(inflight.id, after_rotation.id, "inflight ping must not rotate");

        let (db_id, db_old_id, _) = fetch_row_state(pool).await;
        assert_eq!(db_id, after_rotation.id);
        assert_eq!(db_old_id, created.id);
    }

    #[saps::db_test]
    async fn test_ping_with_old_id_outside_grace_period_returns_none() {
        let session = AuthSession::new(TestRole::Customer);
        let created = AuthPostGresDescriptor::<TestDbHandle>::create_auth_session(session)
            .await
            .expect("create session");

        // Rotate the session.
        saps::sqlx::query(
            "UPDATE saps.auth_sessions \
             SET date_created = NOW() - INTERVAL '10 minutes' \
             WHERE id = $1",
        )
        .bind(created.id)
        .execute(pool)
        .await
        .expect("backdate before rotation");

        let after_rotation =
            AuthPostGresDescriptor::<TestDbHandle>::ping_auth_session::<TestRole>(
                30,
                &created.id.to_string(),
            )
            .await
            .expect("ping rotates")
            .expect("session exists");
        assert_ne!(after_rotation.id, created.id);

        // Push time_minted past the 10s grace window.
        saps::sqlx::query(
            "UPDATE saps.auth_sessions \
             SET time_minted = NOW() - INTERVAL '30 seconds' \
             WHERE id = $1",
        )
        .bind(after_rotation.id)
        .execute(pool)
        .await
        .expect("backdate time_minted");

        let result =
            AuthPostGresDescriptor::<TestDbHandle>::ping_auth_session::<TestRole>(
                30,
                &created.id.to_string(),
            )
            .await
            .expect("ping with stale old_id");
        assert!(result.is_none(), "grace period must have expired");

        // The row itself is still present and untouched (only the lookup failed).
        let (db_id, db_old_id, _) = fetch_row_state(pool).await;
        assert_eq!(db_id, after_rotation.id);
        assert_eq!(db_old_id, created.id);
    }

    #[saps::db_test]
    async fn test_ping_with_old_id_does_not_trigger_second_rotation() {
        let session = AuthSession::new(TestRole::Admin);
        let created = AuthPostGresDescriptor::<TestDbHandle>::create_auth_session(session)
            .await
            .expect("create session");

        // First rotation.
        saps::sqlx::query(
            "UPDATE saps.auth_sessions \
             SET date_created = NOW() - INTERVAL '10 minutes' \
             WHERE id = $1",
        )
        .bind(created.id)
        .execute(pool)
        .await
        .expect("backdate");

        let after_rotation =
            AuthPostGresDescriptor::<TestDbHandle>::ping_auth_session::<TestRole>(
                30,
                &created.id.to_string(),
            )
            .await
            .expect("rotates")
            .expect("session exists");

        // Backdate the *new* date_created so that a current-id ping would
        // rotate again. We then ping with the OLD id and confirm no rotation
        // happens (grace-period match must not re-rotate).
        saps::sqlx::query(
            "UPDATE saps.auth_sessions \
             SET date_created = NOW() - INTERVAL '10 minutes' \
             WHERE id = $1",
        )
        .bind(after_rotation.id)
        .execute(pool)
        .await
        .expect("backdate post-rotation");

        let grace_ping =
            AuthPostGresDescriptor::<TestDbHandle>::ping_auth_session::<TestRole>(
                30,
                &created.id.to_string(),
            )
            .await
            .expect("ping via old id")
            .expect("session exists");
        assert_eq!(
            grace_ping.id, after_rotation.id,
            "grace-period ping must not rotate the session again"
        );

        let (db_id, db_old_id, _) = fetch_row_state(pool).await;
        assert_eq!(db_id, after_rotation.id);
        assert_eq!(db_old_id, created.id);
    }

    #[saps::db_test]
    async fn test_expired_session_deleted_when_pinged_via_old_id() {
        let session = AuthSession::new(TestRole::Admin);
        let created = AuthPostGresDescriptor::<TestDbHandle>::create_auth_session(session)
            .await
            .expect("create session");

        // Rotate first so old_id != id.
        saps::sqlx::query(
            "UPDATE saps.auth_sessions \
             SET date_created = NOW() - INTERVAL '10 minutes' \
             WHERE id = $1",
        )
        .bind(created.id)
        .execute(pool)
        .await
        .expect("backdate");

        let _ = AuthPostGresDescriptor::<TestDbHandle>::ping_auth_session::<TestRole>(
            30,
            &created.id.to_string(),
        )
        .await
        .expect("rotates")
        .expect("session exists");

        // Now make last_interacted very old so the session is considered expired.
        saps::sqlx::query(
            "UPDATE saps.auth_sessions \
             SET last_interacted = NOW() - INTERVAL '2 hours' \
             WHERE old_id = $1",
        )
        .bind(created.id)
        .execute(pool)
        .await
        .expect("expire session");

        let result = AuthPostGresDescriptor::<TestDbHandle>::ping_auth_session::<TestRole>(
            30,
            &created.id.to_string(),
        )
        .await
        .expect("ping expired via old_id");
        assert!(result.is_none(), "expired session must be evicted");

        let row = saps::sqlx::query("SELECT id FROM saps.auth_sessions")
            .fetch_optional(pool)
            .await
            .expect("fetch");
        assert!(row.is_none(), "expired session row should be deleted");
    }
}
